import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  desktopSidebar: [
    {
      type: 'category',
      label: 'LX-M 桌面版',
      link: { type: 'doc', id: 'desktop/index'},
      items: [
        {
          type: 'category',
          label: '常见问题',
          link: {type: 'doc', id: 'desktop/faq/index'},
          items: [
            {type: 'autogenerated', dirName: 'desktop/faq'},
          ],
        },
        {
          type: 'doc',
          id: 'desktop/custom-source',
          label: '自定义音源',
        },
        {
          type: 'doc',
          id: 'desktop/ext-source-plugin',
          label: '扩展音源插件',
        },
        {
          type: 'doc',
          id: 'desktop/cookie-sync',
          label: 'Cookie 同步设置',
        },
        {
          type: 'doc',
          id: 'desktop/datapath',
          label: '数据存储路径',
        },
        {
          type: 'doc',
          id: 'desktop/use-source-code',
          label: '源码使用方法',
        },
        {
          type: 'doc',
          id: 'desktop/license',
          label: '许可协议',
        },
      ],
    },
    {
      type: 'category',
      label: '应用文档（自动同步）',
      link: {type: 'doc', id: 'upstream/readme'},
      items: [
        {type: 'doc', id: 'upstream/faq', label: '常见问题（上游 FAQ）'},
        {type: 'doc', id: 'upstream/changelog', label: '更新日志'},
        {type: 'doc', id: 'upstream/win7-compatibility', label: 'Win7 兼容说明'},
      ],
    },
  ],
};

export default sidebars;
